name = "pack1"
author = "moistpony"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05d63879d6c0041e8bc61798fef15a90345e8aee3d71f1a963fdef626445f714"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.65-beta"

[options]
pack-url = "https://db.willtryon.com/pack.toml"
