name = "pack1"
author = "moistpony"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef412491da059abc6db59f7c69da520a33ce7b02c2c4060eda13d67e818cd0e3"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.65-beta"

[options]
pack-url = "https://mcclientlatest.willtryon.com/pack.toml"
