name = "pack1"
author = "moistpony"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9f78ec57c038dbf613016b4445b208cffa253cf41b10c1e351ac8e5d193268c"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.65-beta"

[options]
pack-url = "https://db.willtryon.com/pack.toml"
